Cypress.on('uncaught:exception', (err, runnable) => {
  return false
})

describe('Flow Contact Company', () => {
  it('passed', () => {
    cy.Login(Cypress.env('EMAIL_HOLDING_USER'), Cypress.env('PASSWORD')).then(() => {
      cy.wait(500).get('#sidebar_contact').click({ force: true })
      cy.wait(500).get('#sidebar_add_account').click({ force: true })
    })
    cy.reload().then(() => {
      cy.get('body').click()
    })
    cy.wait(500).get('#brcumb_company').click()
    cy.wait(500).get('#table_company').should('be.visible').as('table company detected')
    cy.wait(500).get('body').click()
    //SEARCH DATA
    cy.get('#input_search_company').type('Cafe')
    cy.wait(500).get('#table_company > tbody > tr > [aria-colindex="1"]').contains('Cafe Hermina Pusat')
    cy.get('#input_search_company').clear()
    cy.get('#input_search_company').type('Pasar')
    cy.wait(1500).get('tbody > tr > td > div > .text-center > h4').should('contain', 'No data available in table')
    cy.get('#input_search_company').clear()
    //ADD DATA
    cy.get('#btn_add_company').click()
    cy.wait(500).get('#input_control_code').type('CMP-001')
    cy.wait(500).get('#input_name').type('PT.INDO JAYA BAHAGIA')
    cy.wait(500).get('#input_tax_number').type('0436650001')
    cy.wait(500).get('#input_license_number').type('720202045')
    cy.wait(500).get('#input_class').select('Supplier')
    cy.wait(500).get('#input_country').select('INDONESIA')
    cy.wait(500).get('#input_sales_tax_id').type('2270')
    cy.wait(500).get('#submit_company').click()
    cy.wait(1000).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('#table_company > tbody > tr > [aria-colindex="1"]').contains('PT.INDO JAYA BAHAGIA')
    //EDIT DATA
    cy.get('#btn_dropdown_company_0__BV_toggle_').click()
    cy.get('#btn_edit_company_0').click()
    cy.wait(500).get('#input_control_code').clear()
    cy.wait(500).get('#input_control_code').type('CMP-001')
    cy.wait(500).get('#input_name').clear()
    cy.wait(500).get('#input_name').type('PT.INDO JAYA BAHAGIA EDIT')
    cy.wait(500).get('#input_tax_number').clear()
    cy.wait(500).get('#input_tax_number').type('0436650001')
    cy.wait(500).get('#input_license_number').clear()
    cy.wait(500).get('#input_license_number').type('720202045')
    cy.wait(500).get('#input_class').invoke('val', '')
    cy.wait(500).get('#input_class').select('Supplier')
    cy.wait(500).get('#input_country').invoke('val', '')
    cy.wait(500).get('#input_country').select('INDONESIA')
    cy.wait(500).get('#input_sales_tax_id').clear()
    cy.wait(500).get('#input_sales_tax_id').type('2270')
    cy.wait(500).get('#submit_company').click()
    cy.wait(1000).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('#table_company > tbody > tr > [aria-colindex="1"]').contains('PT.INDO JAYA BAHAGIA EDIT')
    //DELETE DATA
    cy.get('#btn_dropdown_company_0__BV_toggle_').click()
    cy.get('#btn_delete_company_0').click()
    cy.wait(500).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('.swal2-confirm').click()
    cy.wait(500).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('#table_company > tbody > tr > [aria-colindex="1"]').should('not.contain', 'PT.INDO JAYA BAHAGIA EDIT')

  })
})