Cypress.on('uncaught:exception', (err, runnable) => {
  return false
})

describe('Flow Contacts Person', () => {
  it('passed', () => {
    cy.Login(Cypress.env('EMAIL_HOLDING_USER'), Cypress.env('PASSWORD')).then(() => {
      cy.wait(500).get('#sidebar_contact').click({ force: true })
      cy.wait(500).get('#sidebar_add_account').click({ force: true })
    })
    cy.reload().then(() => {
      cy.get('body').click()
    })
    cy.wait(500).get('#brcumb_person').click()
    cy.wait(500).get('#table_person').should('be.visible').as('table company detected')
    cy.wait(500).get('body').click()
    //SEARCH DATA
    cy.get('#input_search_person').type('MUFID')
    cy.wait(500).get('#table_person > tbody > :nth-child(1) > [aria-colindex="1"]').contains('MUFID')
    cy.get('#input_search_person').clear()
    cy.get('#input_search_person').type('ezekiel')
    cy.wait(1500).get('#table_person > tbody > tr > td > div > .text-center > h4').should('contain', 'No data available in table')
    cy.get('#input_search_person').clear()
    //ADD DATA
    cy.get('#btn_add_person').click()
    cy.wait(500).get('#form_person').should('be.visible')
    cy.wait(500).get('#input_control_code_person').type('TKH-062')
    cy.wait(500).get('#input_class_person').select('Member')
    cy.wait(500).get('#input_salutation_person').select('Mr.')
    cy.wait(500).get('#input_given_name_person').type('TAKAHIRO')
    cy.wait(500).get('#input_middle_name_person').type('MINATO')
    cy.wait(500).get('#input_surname_person').type('SOUMA')
    cy.wait(500).get('#input_country_person').select('INDONESIA')
    cy.wait(500).get('#input_personal_id_person').type('3202320507128989')
    cy.wait(500).get('#input_birthdate_person').type('1996-12-01')
    cy.wait(500).get('#submit_person').click()
    cy.wait(1000).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('#table_person > tbody > :nth-child(1) > [aria-colindex="1"]').contains('TAKAHIRO MINATO SOUMA')
    //EDIT DATA
    cy.get('#btn_dropdown_person_0__BV_toggle_').click()
    cy.get('#btn_edit_person_0').click()
    cy.wait(500).get('#form_person').should('be.visible')
    cy.wait(500).get('#input_control_code_person').clear()
    cy.wait(500).get('#input_control_code_person').type('AEN-001')
    cy.wait(500).get('#input_class_person').invoke('val', '')
    cy.wait(500).get('#input_class_person').select('Member')
    cy.wait(500).get('#input_salutation_person').invoke('val', '')
    cy.wait(500).get('#input_salutation_person').select('Mr.')
    cy.wait(500).get('#input_given_name_person').clear()
    cy.wait(500).get('#input_given_name_person').type('AULUS')
    cy.wait(500).get('#input_middle_name_person').clear()
    cy.wait(500).get('#input_middle_name_person').type('ESTES')
    cy.wait(500).get('#input_surname_person').clear()
    cy.wait(500).get('#input_surname_person').type('NOVARIA')
    cy.wait(500).get('#input_country_person').invoke('val', '')
    cy.wait(500).get('#input_country_person').select('INDONESIA')
    cy.wait(500).get('#input_personal_id_person').clear()
    cy.wait(500).get('#input_personal_id_person').type('3202320507128989')
    cy.wait(500).get('#input_birthdate_person').clear()
    cy.wait(500).get('#input_birthdate_person').type('1996-12-01')
    cy.wait(500).get('#submit_person').click()
    cy.wait(1000).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('#table_person > tbody > :nth-child(1) > [aria-colindex="1"]').contains('AULUS ESTES NOVARIA')
    //DELETE DATA
    cy.get('#btn_dropdown_person_0__BV_toggle_').click()
    cy.get('#btn_delete_person_0').click()
    cy.wait(500).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('.swal2-confirm').click()
    cy.wait(500).get('.swal2-popup').should('be.visible')
    cy.wait(500).get('#table_person > tbody > :nth-child(1) > [aria-colindex="1"]').should('not.contain', 'AULUS ESTES NOVARIA')
  })
})