name: Cypress Tests
on: [push, pull_request]
jobs:
  parallel-runs-across-platforms:
    name: every OS
    strategy:
      matrix:
        # run 3 copies of the current job in parallel
        # and they will load balance all specs
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        machines: [1, 2, 3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run tests
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          record: true
          parallel: true # Runs test in parallel using settings above
          group: Parallel 3x on ${{ matrix.os }}
          # on Mac and Linux we can use "npm start"
          start: npm start --force
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
